export default function About() {
    return (
        <div className="my-3">
            <h1>About</h1>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Mollitia eveniet dicta autem dolorem molestias iusto a? Unde at, maxime, accusamus tenetur optio nam rerum quaerat ex voluptas similique eveniet in mollitia debitis reiciendis est doloribus itaque quia. Saepe temporibus quos ab voluptates, nostrum porro, nihil, doloremque itaque suscipit sequi reiciendis.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Eaque vero cupiditate veritatis in enim eos perferendis natus, nisi impedit explicabo, necessitatibus vitae. Quas necessitatibus libero architecto harum natus molestias, iste hic quidem est aliquid consequatur nulla illum dignissimos. Facilis porro architecto accusamus quos? Deserunt voluptas cupiditate temporibus tempora provident error veniam molestias officiis officia! Dignissimos, totam modi ut similique tenetur libero fugiat reprehenderit corrupti provident deserunt ducimus saepe aliquam velit sequi molestiae labore rem accusamus eaque asperiores, quo quod odio.</p>
            <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vero ipsam molestias mollitia fugit perspiciatis aperiam repellendus incidunt, nam atque, laboriosam expedita aspernatur. Deserunt consequuntur harum quo consequatur, laudantium magnam quisquam.</p>
            <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Voluptas libero dicta dolores similique sint eum autem? Fugit quasi quisquam animi? Exercitationem error veritatis ut, eum aliquam, ad esse voluptatum harum eos enim temporibus culpa fugiat dignissimos odit commodi. Labore provident quos nesciunt earum, architecto, dolorem asperiores repellendus accusantium nulla nemo illum unde fugit iusto. Soluta explicabo ex aperiam fuga temporibus, consequatur enim? Consequuntur, ipsa. Corporis, inventore totam fugiat dignissimos laborum cumque nisi minus, nobis in provident accusantium quo ipsa iure sint nihil harum saepe labore pariatur? Nam nostrum quas amet quae veniam nemo sed perferendis modi error eius, ad soluta.</p>
        </div>
    );
}